// src/constants/fake-api/gateway.js
const FAKE_API = {
    '/Manager/SelectGatewayInfoPage': {
        "result": true,
        "extra": null,
        "error": 0,
        "message": null,
        "remoteIp": null,
        "totalCount": 48,
        "gatewayInfoList": [
            {
                "gatewayInfoId": 245,
                "organizationCode": "test_ella",
                "serialNumber": "B000001",
                "macAddress": "08:D5:C0:20:00:A0",
                "ip": null,
                "wardCode": null,
                "sickRoomCode": null,
                "floor": "13층13층",
                "lcNumber": null,
                "fwVersion": "1",
                "connStatus": 1,
                "processStatus": 0,
                "connStatusUpdateTime": null,
                "connStatusUpdateTimeByStream": null,
                "gatewayErrorCode": 0,
                "axisX": 0,
                "axisY": 0,
                "updateFwVersion": null,
                "fwUpdateDateTime": null,
                "deactivate": 0,
                "etc": "test",
                "updateDateTime": "2025-01-07 10:03:09",
                "buildingCode": null
            },
            {
                "gatewayInfoId": 147,
                "organizationCode": "THYNC",
                "serialNumber": "B000761",
                "macAddress": "08:D5:C0:20:02:F9",
                "ip": null,
                "wardCode": null,
                "sickRoomCode": null,
                "floor": null,
                "lcNumber": null,
                "fwVersion": "1.5.11",
                "connStatus": 1,
                "processStatus": 0,
                "connStatusUpdateTime": null,
                "connStatusUpdateTimeByStream": "2024-07-01 18:14:03",
                "gatewayErrorCode": 0,
                "axisX": 0,
                "axisY": 0,
                "updateFwVersion": null,
                "fwUpdateDateTime": "2024-06-28 15:24:40",
                "deactivate": 0,
                "etc": null,
                "updateDateTime": "2024-06-28 15:24:40",
                "buildingCode": null
            },
            {
                "gatewayInfoId": 224,
                "organizationCode": "THYNC",
                "serialNumber": "B000764",
                "macAddress": "08:D5:C0:23:02:01",
                "ip": null,
                "wardCode": null,
                "sickRoomCode": null,
                "floor": null,
                "lcNumber": null,
                "fwVersion": "1.6.2",
                "connStatus": 1,
                "processStatus": 0,
                "connStatusUpdateTime": null,
                "connStatusUpdateTimeByStream": "2025-03-07 08:07:37",
                "gatewayErrorCode": 0,
                "axisX": 0,
                "axisY": 0,
                "updateFwVersion": null,
                "fwUpdateDateTime": "2025-03-07 08:12:58",
                "deactivate": 0,
                "etc": null,
                "updateDateTime": "2025-03-07 08:12:58",
                "buildingCode": null
            },
            {
                "gatewayInfoId": 154,
                "organizationCode": "THYNC",
                "serialNumber": "B000769",
                "macAddress": "08:D5:C0:20:03:01",
                "ip": null,
                "wardCode": null,
                "sickRoomCode": null,
                "floor": null,
                "lcNumber": null,
                "fwVersion": "1.6.2",
                "connStatus": 1,
                "processStatus": 0,
                "connStatusUpdateTime": null,
                "connStatusUpdateTimeByStream": "2025-03-18 14:38:52",
                "gatewayErrorCode": 0,
                "axisX": 0,
                "axisY": 0,
                "updateFwVersion": null,
                "fwUpdateDateTime": "2025-02-25 14:17:52",
                "deactivate": 0,
                "etc": null,
                "updateDateTime": "2025-02-25 14:17:52",
                "buildingCode": null
            },
            {
                "gatewayInfoId": 251,
                "organizationCode": "DEMO_ORG",
                "serialNumber": "B000813",
                "macAddress": "08:D5:C0:20:03:2D",
                "ip": null,
                "wardCode": null,
                "sickRoomCode": null,
                "floor": null,
                "lcNumber": null,
                "fwVersion": "1.6.0",
                "connStatus": 1,
                "processStatus": 0,
                "connStatusUpdateTime": null,
                "connStatusUpdateTimeByStream": "2025-02-05 15:10:21",
                "gatewayErrorCode": 0,
                "axisX": 0,
                "axisY": 0,
                "updateFwVersion": null,
                "fwUpdateDateTime": null,
                "deactivate": 0,
                "etc": "평촌 한림대 응급실",
                "updateDateTime": "2025-02-03 13:52:17",
                "buildingCode": null
            }
        ]
    }
};
const RUN = function() {
    for (const key in FAKE_API) {
        window.CONSTANTS.set(`${window.CONSTANTS.get(`APP.API_BASE`)}${key}`, FAKE_API[key], true);
    }
};
export { RUN };