// src/constants/fake-api/organ.js
const FAKE_API = {
    '/Manager/SelectOrganizationPage': {
        "result": true,
        "extra": null,
        "error": 0,
        "message": null,
        "remoteIp": null,
        "totalCount": 25,
        "organizationList": [
            {
                "organizationId": 35,
                "organizationCode": "PHGIDOK",
                "organizationType": 0,
                "organizationInfo": "포항세명기독병원",
                "systemManager": "teo.kang@seerstech.com",
                "syncHis": 0,
                "deviceManagerType": 1,
                "organizationName": "포항세명기독병원",
                "countryCode": "KR",
                "countryName": "Republic of Korea",
                "state": "Gyeonggi-do",
                "city": "Sujeong-gu, Seongnam-si",
                "address": "76, Bokjeong-ro",
                "latitude": 37.0,
                "longitude": 127.0,
                "phoneNumber": "+8224947582",
                "level": 10,
                "expiration": 0,
                "expirationDateTime": "2220-10-27 12:04:24",
                "dateTime": "2021-12-28 17:37:24",
                "gmtCode": "GMT+0900",
                "timezone": "Asia/Seoul",
                "etc": "Seerstech",
                "themeType": 0,
                "userColor": null,
                "userGradient1": null,
                "userGradient2": null,
                "measurementDate": 15,
                "hideName": 1,
                "hideNameType": "*"
            },
            {
                "organizationId": 44,
                "organizationCode": "TEST_ORGAN4",
                "organizationType": 0,
                "organizationInfo": null,
                "systemManager": "ella.choi@seerstech.com",
                "syncHis": 1,
                "deviceManagerType": 1,
                "organizationName": "테스트4",
                "countryCode": "Ko",
                "countryName": "Korea",
                "state": null,
                "city": null,
                "address": null,
                "latitude": 0.0,
                "longitude": 0.0,
                "phoneNumber": null,
                "level": 1,
                "expiration": 0,
                "expirationDateTime": "2100-12-31 23:59:59",
                "dateTime": "2024-11-04 16:04:27",
                "gmtCode": "GMT+0900",
                "timezone": "Asia/Seoul",
                "etc": "비고1",
                "themeType": 0,
                "userColor": null,
                "userGradient1": null,
                "userGradient2": null,
                "measurementDate": 15,
                "hideName": 2,
                "hideNameType": "*"
            },
            {
                "organizationId": 19,
                "organizationCode": "TEST-ZAID2",
                "organizationType": 0,
                "organizationInfo": null,
                "systemManager": "zaid.yoon@seerstech.com",
                "syncHis": 0,
                "deviceManagerType": 0,
                "organizationName": "테스트-자이드2",
                "countryCode": "Ko",
                "countryName": "Korea",
                "state": null,
                "city": null,
                "address": null,
                "latitude": 0.0,
                "longitude": 0.0,
                "phoneNumber": null,
                "level": 1,
                "expiration": 0,
                "expirationDateTime": "2100-12-31 23:59:59",
                "dateTime": "2024-06-17 13:51:59",
                "gmtCode": "GMT+0900",
                "timezone": "Asia/Seoul",
                "etc": "테스트후 삭제 예정",
                "themeType": 0,
                "userColor": null,
                "userGradient1": null,
                "userGradient2": null,
                "measurementDate": 15,
                "hideName": 1,
                "hideNameType": "*"
            },
            {
                "organizationId": 20,
                "organizationCode": "test_ella",
                "organizationType": 0,
                "organizationInfo": null,
                "systemManager": null,
                "syncHis": 0,
                "deviceManagerType": 0,
                "organizationName": "테스트-엘라",
                "countryCode": "Ko",
                "countryName": "Korea",
                "state": null,
                "city": null,
                "address": null,
                "latitude": 0.0,
                "longitude": 0.0,
                "phoneNumber": null,
                "level": 1,
                "expiration": 0,
                "expirationDateTime": "2100-12-31 23:59:59",
                "dateTime": "2024-06-18 09:03:44",
                "gmtCode": "GMT+0900",
                "timezone": "Asia/Seoul",
                "etc": null,
                "themeType": 0,
                "userColor": null,
                "userGradient1": null,
                "userGradient2": null,
                "measurementDate": 15,
                "hideName": 1,
                "hideNameType": "*"
            },
            {
                "organizationId": 38,
                "organizationCode": "WBLE",
                "organizationType": 0,
                "organizationInfo": null,
                "systemManager": null,
                "syncHis": 0,
                "deviceManagerType": 0,
                "organizationName": "웨어러블랩",
                "countryCode": "Ko",
                "countryName": "Korea",
                "state": null,
                "city": null,
                "address": null,
                "latitude": 0.0,
                "longitude": 0.0,
                "phoneNumber": null,
                "level": 1,
                "expiration": 0,
                "expirationDateTime": "2100-12-31 23:59:59",
                "dateTime": "2024-09-27 08:26:55",
                "gmtCode": "GMT+0900",
                "timezone": "Asia/Seoul",
                "etc": null,
                "themeType": 0,
                "userColor": null,
                "userGradient1": null,
                "userGradient2": null,
                "measurementDate": 15,
                "hideName": 1,
                "hideNameType": "*"
            },
            {
                "organizationId": 54,
                "organizationCode": "YeppaTest",
                "organizationType": 0,
                "organizationInfo": null,
                "systemManager": null,
                "syncHis": 0,
                "deviceManagerType": 0,
                "organizationName": "예파테스트",
                "countryCode": "Ko",
                "countryName": "Korea",
                "state": null,
                "city": null,
                "address": null,
                "latitude": 0.0,
                "longitude": 0.0,
                "phoneNumber": null,
                "level": 1,
                "expiration": 0,
                "expirationDateTime": "2100-12-31 23:59:59",
                "dateTime": "2025-01-02 14:09:17",
                "gmtCode": "GMT+0900",
                "timezone": "Asia/Seoul",
                "etc": null,
                "themeType": 0,
                "userColor": null,
                "userGradient1": null,
                "userGradient2": null,
                "measurementDate": 100,
                "hideName": 1,
                "hideNameType": "*"
            },
            {
                "organizationId": 12,
                "organizationCode": "THYNC",
                "organizationType": 0,
                "organizationInfo": "세부정보3",
                "systemManager": "teo.kang@seerstech.com",
                "syncHis": 1,
                "deviceManagerType": 0,
                "organizationName": "씽크",
                "countryCode": "KR",
                "countryName": "Republic of Korea",
                "state": "Gyeonggi-do",
                "city": "Sujeong-gu, Seongnam-si",
                "address": "76, Bokjeong-ro",
                "latitude": 37.0,
                "longitude": 127.0,
                "phoneNumber": "+8224947582",
                "level": 10,
                "expiration": 0,
                "expirationDateTime": "2220-10-27 12:04:24",
                "dateTime": "2021-12-28 17:37:24",
                "gmtCode": "GMT+0900",
                "timezone": "Asia/Seoul",
                "etc": "Seerstech",
                "themeType": 0,
                "userColor": null,
                "userGradient1": null,
                "userGradient2": null,
                "measurementDate": 20,
                "hideName": 2,
                "hideNameType": "*"
            },
            {
                "organizationId": 11,
                "organizationCode": "SEERS",
                "organizationType": 0,
                "organizationInfo": "세부정보311",
                "systemManager": "teo.kang@seerstech.com",
                "syncHis": 1,
                "deviceManagerType": 1,
                "organizationName": "씨어스테크놀로지1",
                "countryCode": "KR",
                "countryName": "Republic of Korea",
                "state": "Gyeonggi-do",
                "city": "Sujeong-gu, Seongnam-si",
                "address": "76, Bokjeong-ro",
                "latitude": 37.0,
                "longitude": 127.0,
                "phoneNumber": "+8224947582",
                "level": 10,
                "expiration": 0,
                "expirationDateTime": "2220-10-27 12:04:24",
                "dateTime": "2021-12-28 17:37:24",
                "gmtCode": "GMT+0900",
                "timezone": "Asia/Seoul",
                "etc": "Seerstech",
                "themeType": 0,
                "userColor": null,
                "userGradient1": null,
                "userGradient2": null,
                "measurementDate": 15,
                "hideName": 1,
                "hideNameType": "*"
            },
            {
                "organizationId": 37,
                "organizationCode": "LOGAN_TEST_ORG",
                "organizationType": 0,
                "organizationInfo": null,
                "systemManager": "logan.kang@seerstech.com",
                "syncHis": 0,
                "deviceManagerType": 0,
                "organizationName": "로건기관1",
                "countryCode": "Ko",
                "countryName": "Korea",
                "state": null,
                "city": null,
                "address": null,
                "latitude": 0.0,
                "longitude": 0.0,
                "phoneNumber": null,
                "level": 1,
                "expiration": 0,
                "expirationDateTime": "2100-12-31 23:59:59",
                "dateTime": "2024-09-23 11:42:32",
                "gmtCode": "GMT+0900",
                "timezone": "Asia/Seoul",
                "etc": null,
                "themeType": 0,
                "userColor": null,
                "userGradient1": null,
                "userGradient2": null,
                "measurementDate": 15,
                "hideName": 1,
                "hideNameType": "*"
            },
            {
                "organizationId": 46,
                "organizationCode": "AYAAN",
                "organizationType": 0,
                "organizationInfo": null,
                "systemManager": null,
                "syncHis": 0,
                "deviceManagerType": 0,
                "organizationName": "디바이스테스트",
                "countryCode": "Ko",
                "countryName": "Korea",
                "state": null,
                "city": null,
                "address": null,
                "latitude": 0.0,
                "longitude": 0.0,
                "phoneNumber": null,
                "level": 1,
                "expiration": 0,
                "expirationDateTime": "2100-12-31 23:59:59",
                "dateTime": "2024-11-05 08:32:56",
                "gmtCode": "GMT+0900",
                "timezone": "Asia/Seoul",
                "etc": null,
                "themeType": 0,
                "userColor": null,
                "userGradient1": null,
                "userGradient2": null,
                "measurementDate": 15,
                "hideName": 1,
                "hideNameType": "*"
            }
        ]
    }
};
const RUN = function() {
    for (const key in FAKE_API) {
        window.CONSTANTS.set(`${window.CONSTANTS.get(`APP.API_BASE`)}${key}`, FAKE_API[key], true);
    }
};
export { RUN };